# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: karma

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('etc/karma.yml') }}
    - uses: conda-incubator/setup-miniconda@v1
      with:
        python-version: 3.6
        auto-update-conda: true
        activate-environment: karma
        channel-priority: flexible
        environment-file: etc/karma.yml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black
    - name: Code format with black
      run: |
        black --check ${GITHUB_WORKSPACE}
    - name: Test with pytest
      run: |
        pytest ${GITHUB_WORKSPACE}
